//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesos
    {
        public int IdAccesos { get; set; }
        public Nullable<int> TipoUsuarioId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Menus Menus1 { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual TipoUsuario TipoUsuario1 { get; set; }
    }
}
