//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC1
    {
        public int AbsEntry { get; set; }
        public int Line { get; set; }
        public string srcPath { get; set; }
        public string trgtPath { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UsrID { get; set; }
        public string Copied { get; set; }
        public string Override { get; set; }
        public string subPath { get; set; }
        public string FreeText { get; set; }
    }
}
