//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatarraDetalle
    {
        public int ChatarraDetalleId { get; set; }
        public Nullable<int> ChatarraId { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string CodigoItem { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PesoTeoricoUnitario { get; set; }
        public Nullable<decimal> PesoTeoricoTotal { get; set; }
        public Nullable<decimal> PesoUnitarioAjustado { get; set; }
        public Nullable<decimal> PesoTotalAjustado { get; set; }
    
        public virtual Chatarra Chatarra { get; set; }
    }
}
