//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatarraPesos
    {
        public int ChatarraPesoId { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<decimal> PesoTeoricoTotalCalculado { get; set; }
        public Nullable<decimal> PesoBultoIngresado { get; set; }
        public Nullable<decimal> PesoAjustadoTotal { get; set; }
        public string Desviacion { get; set; }
        public Nullable<int> CantidadTotal { get; set; }
        public Nullable<int> ModoIngreso { get; set; }
    }
}
