//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CronogramaExportacion
    {
        public int CronogramaExportacionId { get; set; }
        public string Orden { get; set; }
        public string Cliente { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<System.DateTime> FechaDespacho { get; set; }
        public Nullable<int> Booking { get; set; }
        public Nullable<int> TotalContenedores { get; set; }
        public string CardCode { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> FechaZarpe { get; set; }
    }
}
