//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBODACARPRODEntities1 : DbContext
    {
        public SBODACARPRODEntities1()
            : base("name=SBODACARPRODEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OCRD> OCRD { get; set; }
        public virtual DbSet<vConsultaArticulos> vConsultaArticulos { get; set; }
        public virtual DbSet<VU_REPORTEPRODUCCION> VU_REPORTEPRODUCCION { get; set; }
        public virtual DbSet<IGN1> IGN1 { get; set; }
        public virtual DbSet<OIGN> OIGN { get; set; }
        public virtual DbSet<OITM> OITM { get; set; }
        public virtual DbSet<OPDN> OPDN { get; set; }
        public virtual DbSet<PDN1> PDN1 { get; set; }
        public virtual DbSet<ORDR> ORDR { get; set; }
        public virtual DbSet<RDR1> RDR1 { get; set; }
        public virtual DbSet<vReporteGeneralVentasJO> vReporteGeneralVentasJO { get; set; }
        public virtual DbSet<C_SYP_CLASESN> C_SYP_CLASESN { get; set; }
        public virtual DbSet<C_SYP_LINEASN> C_SYP_LINEASN { get; set; }
        public virtual DbSet<OCRG> OCRG { get; set; }
        public virtual DbSet<INV1> INV1 { get; set; }
        public virtual DbSet<OINV> OINV { get; set; }
    }
}
