//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosTecnicosBatExporListCli
    {
        public int DatosTecnicosBatExporListCliId { get; set; }
        public Nullable<int> NombreListaId { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> C20 { get; set; }
        public Nullable<int> CAP { get; set; }
        public Nullable<int> CCAMenos18CLocal { get; set; }
        public Nullable<int> CA0C { get; set; }
        public Nullable<int> CCAMenos18CExpo { get; set; }
        public Nullable<decimal> PesoSellada { get; set; }
        public Nullable<decimal> PesoHumedaKg { get; set; }
        public Nullable<int> CantidadPiso { get; set; }
        public Nullable<int> Pisos { get; set; }
        public Nullable<int> CantidadPorPallet { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual NombreListaPrecioCliente NombreListaPrecioCliente { get; set; }
    }
}
