//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosTecnicosCalidadBaterias
    {
        public int DatosTecnicosCalidadBateriasId { get; set; }
        public string Modelo { get; set; }
        public string CAP { get; set; }
        public string RC { get; set; }
        public string CCA { get; set; }
        public string CACeroGrados { get; set; }
        public string CCAMenosDiescochoExpo { get; set; }
        public string C20xDiseno { get; set; }
        public string CapResxDiseno { get; set; }
        public string CCAxDisenoSeparadorFibra { get; set; }
        public string CAxDisenoSeparadorFibra { get; set; }
        public string HCAxDisenoSeparadorFibra { get; set; }
        public string CCAxDisenoSeparadorPE { get; set; }
        public string CAxDisenoSeparadorPE { get; set; }
        public string HCAxDisenoSeparadorPE { get; set; }
        public string CantPlacas { get; set; }
        public string PesoSellada { get; set; }
        public string PesoHumedaKg { get; set; }
        public string Linea { get; set; }
    }
}
