//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleGeneralPackingList
    {
        public int DetalleGeneralPackingListId { get; set; }
        public Nullable<int> PackingId { get; set; }
        public string ClientePackingList { get; set; }
        public string ContenedorPackingList { get; set; }
        public Nullable<System.DateTime> FechaPackingList { get; set; }
        public string ReservaPackingList { get; set; }
        public string FacturaPedido { get; set; }
        public string PedidoPackingList { get; set; }
        public string EmbarcacionPackingList { get; set; }
        public string IntercambioEirPackingList { get; set; }
        public string ReferenciasPackingList { get; set; }
        public string ProductosPackingList { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
