//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesClientes
    {
        public int DireccionesClientesId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string NombreSucursal { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<decimal> MaximumWeight { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
