//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoMedicionPalletLocal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncabezadoMedicionPalletLocal()
        {
            this.PackingDtlLocal = new HashSet<PackingDtlLocal>();
        }
    
        public int EncabezadoMedicionPalletLocalId { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> NumeroDocumento { get; set; }
        public string NumeroOrden { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> Liberacion { get; set; }
        public Nullable<System.DateTime> FechaLiberacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackingDtlLocal> PackingDtlLocal { get; set; }
    }
}
