//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericosItem
    {
        public int GenericoItemId { get; set; }
        public string GrupoGenericoItem { get; set; }
        public string ModeloDacar { get; set; }
        public string NumeroParteCliente { get; set; }
        public string EtiquetaDatosTecnicos { get; set; }
        public string Polaridad { get; set; }
        public string TipoTerminal { get; set; }
        public Nullable<int> CantidadPiso { get; set; }
        public Nullable<int> PisoMaximo { get; set; }
        public Nullable<int> BateriasPallet { get; set; }
        public Nullable<decimal> PesoTara { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
