//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaPackingList
    {
        public int GuiaPackingListId { get; set; }
        public Nullable<int> PackingId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoTara { get; set; }
        public string RazonSocial { get; set; }
        public string Ruc { get; set; }
        public string Direccion { get; set; }
        public string Placa { get; set; }
        public string SelloA { get; set; }
        public string SelloB { get; set; }
        public string SelloC { get; set; }
        public string SelloD { get; set; }
        public string ElaboradoPor { get; set; }
        public string AutorizadoPor { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string PuntoPartida { get; set; }
    }
}
