//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoRevisionGarantiaTrabajoRealizado
    {
        public int IngresoRevisionGarantiaTrabajoRealizadoId { get; set; }
        public Nullable<int> IngresoRevisionGarantiaId { get; set; }
        public Nullable<bool> PruebaAltaResistencia { get; set; }
        public Nullable<bool> CambioAcido { get; set; }
        public Nullable<bool> RecargaBateria { get; set; }
        public Nullable<bool> InspeccionEstructuraExterna { get; set; }
    
        public virtual IngresoRevisionGarantiaCabecera IngresoRevisionGarantiaCabecera { get; set; }
    }
}
