//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoRevisionGarantiaInspeccionInicial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngresoRevisionGarantiaInspeccionInicial()
        {
            this.IngresoInspeccionInicialDensidadCelda = new HashSet<IngresoInspeccionInicialDensidadCelda>();
        }
    
        public int IngresoRevisionGarantiaInspeccionInicialId { get; set; }
        public Nullable<int> IngresoRevisionGarantiaId { get; set; }
        public Nullable<bool> GolpeadaORota { get; set; }
        public Nullable<bool> Hinchada { get; set; }
        public Nullable<bool> BornesFlojosOHundidos { get; set; }
        public Nullable<bool> BornesFundidos { get; set; }
        public Nullable<bool> ElectrolitoErroneo { get; set; }
        public Nullable<bool> FugaEnCubierta { get; set; }
        public Nullable<bool> FugaEnBornes { get; set; }
        public Nullable<int> CCA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoInspeccionInicialDensidadCelda> IngresoInspeccionInicialDensidadCelda { get; set; }
        public virtual IngresoRevisionGarantiaCabecera IngresoRevisionGarantiaCabecera { get; set; }
    }
}
