//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoInspeccionInicialDensidadCelda
    {
        public int IngresoInspeccionInicialDensidadCeldaId { get; set; }
        public Nullable<int> IngresoRevisionGarantiaInspeccionInicialId { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C5 { get; set; }
        public Nullable<decimal> C6 { get; set; }
    
        public virtual IngresoRevisionGarantiaInspeccionInicial IngresoRevisionGarantiaInspeccionInicial { get; set; }
    }
}
