//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoRevisionGarantiaDiagnostico
    {
        public int IngresoRevisionGarantiaDiagnosticoId { get; set; }
        public Nullable<int> IngresoRevisionGarantiaId { get; set; }
        public Nullable<bool> BateriaEnBuenEstado { get; set; }
        public Nullable<bool> PresentaFalloFabricacion { get; set; }
        public Nullable<bool> DentroPeriodoGarantia { get; set; }
        public Nullable<bool> AplicacionUsoAdecuado { get; set; }
        public Nullable<bool> AplicaGarantia { get; set; }
    
        public virtual IngresoRevisionGarantiaCabecera IngresoRevisionGarantiaCabecera { get; set; }
    }
}
