//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoGarantias
    {
        public int IngresoGarantiaId { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Distribuidor { get; set; }
        public string Ciudad { get; set; }
        public string ModeloBateria { get; set; }
        public string NumeroGarantia { get; set; }
        public Nullable<System.DateTime> RegistroGarantia { get; set; }
        public string Celular { get; set; }
        public string Provincia { get; set; }
        public string MarcaVehiculo { get; set; }
        public string ModeloVehiculo { get; set; }
        public Nullable<int> AnioFabricacion { get; set; }
        public Nullable<decimal> KilometrajeVehiculo { get; set; }
        public string NumeroFactura { get; set; }
    }
}
