//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresosDetallesMedicionCarga
    {
        public int IngresosDetallesMedicionCargaId { get; set; }
        public Nullable<System.DateTime> FechaPrueba { get; set; }
        public Nullable<int> IngresosMedicionCargaId { get; set; }
        public Nullable<decimal> voltaje { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual IngresosMedicionCarga IngresosMedicionCarga { get; set; }
    }
}
