//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITM1
    {
        public string ItemCode { get; set; }
        public short PriceList { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public string Ovrwritten { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public Nullable<decimal> AddPrice1 { get; set; }
        public string Currency1 { get; set; }
        public Nullable<decimal> AddPrice2 { get; set; }
        public string Currency2 { get; set; }
        public string Ovrwrite1 { get; set; }
        public string Ovrwrite2 { get; set; }
        public Nullable<short> BasePLNum { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string PriceType { get; set; }
    }
}
