//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrecioGenerica
    {
        public int ListaPrecioGenericaId { get; set; }
        public string CustomerReference { get; set; }
        public string DacarPartNumber { get; set; }
        public string ModeloGenerico { get; set; }
        public Nullable<int> DimensionsLenght { get; set; }
        public Nullable<int> DimensionWidth { get; set; }
        public Nullable<int> DimensionsHeight { get; set; }
        public string AssemblyBci { get; set; }
        public Nullable<int> SpecificationsNominalCapacity { get; set; }
        public Nullable<int> ReserveCap { get; set; }
        public Nullable<int> CCAMenos18 { get; set; }
        public Nullable<int> CA0 { get; set; }
        public Nullable<decimal> WeightKg { get; set; }
        public Nullable<int> QuantityXLayer { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
