//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrizInventarioBaterias
    {
        public int IdMatriz { get; set; }
        public string Modelo { get; set; }
        public string Referencia { get; set; }
        public string Estado { get; set; }
        public string Polaridad { get; set; }
        public Nullable<int> Linea { get; set; }
    }
}
