//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriz_Inventario_Baterias_RN1
    {
        public Nullable<long> Id { get; set; }
        public string Ubicacion { get; set; }
        public string Refencia { get; set; }
        public string Marca { get; set; }
        public Nullable<decimal> Stock { get; set; }
    }
}
