//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicionPalletPackingLocal
    {
        public int MedicionPalletPackingLocalId { get; set; }
        public Nullable<int> PackingId { get; set; }
        public Nullable<int> Pallet { get; set; }
        public Nullable<int> NumeroMedicion { get; set; }
        public string NumeroLote { get; set; }
        public string Modelo { get; set; }
        public Nullable<decimal> Voltaje { get; set; }
        public Nullable<bool> nivel { get; set; }
        public Nullable<bool> Acabado { get; set; }
        public Nullable<bool> Limpieza { get; set; }
        public Nullable<decimal> CCA { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
