//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCTG
    {
        public short GroupNum { get; set; }
        public string PymntGroup { get; set; }
        public string PayDuMonth { get; set; }
        public Nullable<short> ExtraMonth { get; set; }
        public Nullable<short> ExtraDays { get; set; }
        public Nullable<short> PaymntsNum { get; set; }
        public Nullable<decimal> CredLimit { get; set; }
        public Nullable<decimal> VolumDscnt { get; set; }
        public Nullable<decimal> LatePyChrg { get; set; }
        public Nullable<decimal> ObligLimit { get; set; }
        public Nullable<short> ListNum { get; set; }
        public string Payments { get; set; }
        public Nullable<short> NumOfPmnts { get; set; }
        public Nullable<decimal> Payment1 { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string OpenRcpt { get; set; }
        public string DiscCode { get; set; }
        public string DunningCod { get; set; }
        public string BslineDate { get; set; }
        public Nullable<short> InstNum { get; set; }
        public Nullable<short> TolDays { get; set; }
        public string VATFirst { get; set; }
        public string CrdMthd { get; set; }
        public string CshRelev { get; set; }
    }
}
