//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSLP
    {
        public int SlpCode { get; set; }
        public string SlpName { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Active { get; set; }
        public string Telephone { get; set; }
        public string Mobil { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
    }
}
