//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingListCabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackingListCabecera()
        {
            this.PackingListDetalle = new HashSet<PackingListDetalle>();
        }
    
        public int PackingListId { get; set; }
        public Nullable<int> PalletNumber { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string Customer { get; set; }
        public string Orden { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string CodigoQr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackingListDetalle> PackingListDetalle { get; set; }
    }
}
