//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingDtlLocal
    {
        public int PackingDtlLocalId { get; set; }
        public Nullable<int> IdentificadorCabecera { get; set; }
        public string CodigoItem { get; set; }
        public string DescripcionItem { get; set; }
        public Nullable<int> CantidadItem { get; set; }
    
        public virtual EncabezadoMedicionPalletLocal EncabezadoMedicionPalletLocal { get; set; }
    }
}
