//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletPackingDetalle
    {
        public int PalletPackingDetalleId { get; set; }
        public Nullable<int> PalletPacking { get; set; }
        public Nullable<int> PackingId { get; set; }
        public string ItemCode { get; set; }
        public string DescriptionCode { get; set; }
        public Nullable<int> CantidadItem { get; set; }
    
        public virtual PalletPacking PalletPacking1 { get; set; }
    }
}
