//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletPacking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PalletPacking()
        {
            this.PalletPackingDetalle = new HashSet<PalletPackingDetalle>();
        }
    
        public int PalletPacking1 { get; set; }
        public Nullable<int> PackingId { get; set; }
        public Nullable<int> PalletNumber { get; set; }
        public Nullable<decimal> LargoPallet { get; set; }
        public Nullable<decimal> AnchoPallet { get; set; }
        public Nullable<decimal> AltoPallet { get; set; }
        public Nullable<decimal> VolumenPallet { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public string CodigoQr { get; set; }
    
        public virtual Packing Packing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletPackingDetalle> PalletPackingDetalle { get; set; }
    }
}
