//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoClienteDetalleFinal
    {
        public int PedidoClienteDetalleFinal1 { get; set; }
        public Nullable<int> PedidoClienteCabecera { get; set; }
        public Nullable<int> CantitadTotal { get; set; }
        public Nullable<decimal> PrecioFinalPedido { get; set; }
        public Nullable<decimal> PesoNetoFinalPedido { get; set; }
        public Nullable<decimal> PesoBrutoFinalPedido { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaIngresadaSap { get; set; }
        public Nullable<System.DateTime> FechaNuevaDespacho { get; set; }
        public Nullable<int> CantidadTotalNueva { get; set; }
    }
}
