//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebasLaboratorioCCA
    {
        public int PruebasLaboratorioCCAId { get; set; }
        public Nullable<System.DateTime> FechaPrueba { get; set; }
        public Nullable<int> CodigoIngreso { get; set; }
        public string TipoBateria { get; set; }
        public string Modelo { get; set; }
        public string Separador { get; set; }
        public string LoteEnsamble { get; set; }
        public string LoteCarga { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Voltaje { get; set; }
        public Nullable<decimal> DatoTeoricoPrueba { get; set; }
        public Nullable<decimal> ResultadoFinal { get; set; }
        public Nullable<decimal> rendimiento { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> TipoPruebaCCA { get; set; }
        public string NumeroOrden { get; set; }
    }
}
