//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacarDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguridadUsuario
    {
        public int IdSeguridad { get; set; }
        public Nullable<int> CambioContrasenaDias { get; set; }
        public Nullable<int> DificultadContrasena { get; set; }
        public Nullable<int> Intentos { get; set; }
        public string Estado { get; set; }
    }
}
